### ISSUE TITLE
Update all the image locations to point to docker hub

### ISSUE THREAD

**Issue by hardillb** [flowforge/helm#69]
### Description

And make the build-containers script optional

**Comment by hardillb** [comment]
This should already be done, if the `forge.registry` value is not set then containers will be pulled from docker hub

**Comment by hardillb** [comment]
This needs the doc update to go with it

**Comment by ZJvandeWeg** [comment]
@hardillb Any update on this issue? It's close to the release date, and it's still open.

**Comment by hardillb** [comment]
The docs have been updated.
