### ISSUE TITLE
Publish `index.yaml` to GitHub pages to use helm repositories

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/helm#72]
### I want to: 

```
helm repo add https//flowforge.github.io/helm
helm update
helm upgrade flowforge v1.1.0
```

So that I don't have to download anything when installing on kubernetes from GitHub and can just copy paste all instructions

### Acceptance Criteria

- [ ] helm repository is published
- [ ] the repository can be added and accessed by anyone

See also: https://github.com/helm/chart-releaser

**Comment by hardillb** [comment]
I was planning on looking how to do this with out github pages setup this release. Thanks for the story to remind me to do it.

**Comment by ZJvandeWeg** [comment]
Examples might be:
- https://github.com/grafana/helm-charts/blob/main/.github/workflows/update-helm-repo.yaml
- https://github.com/portainer/k8s/blob/master/.github/workflows/on-push-master-publish-chart.yml#L28-L31

**Comment by hardillb** [comment]
I've done a fist pass at this manually, it should now be live.

I will do a PR to add auto generating this to the release GH Action

**Comment by hardillb** [comment]
It will of course also need a docs PR
